name: Container base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Containers-based:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run services
      run: docker-compose up --build -d

    - name: Wait for Keycloak to be ready
      run: |
        echo "Waiting for 10 seconds for Keycloak to start..."
        sleep 10


    - name: Shut down services
      run: docker-compose down
