name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run services
      run: docker-compose up --build -d

    - name: Wait for Keycloak to be ready
      run: |
        echo "Waiting for Keycloak to start..."
        for i in {1..30}; do
          if curl -s http://localhost:8080/auth > /dev/null; then
            echo "Keycloak is up and running!"
            break
          else
            echo "Waiting for Keycloak..."
            sleep 10
          fi
        done
        if ! curl -s http://localhost:8080/auth > /dev/null; then
          echo "Keycloak failed to start within the expected time."
          exit 1
        fi

    - name: Run tests
      run: docker-compose exec app go test -v ./...

    - name: Run linters
      run: |
        docker-compose exec app go install golang.org/x/lint/golint@latest
        docker-compose exec app golint ./...

    - name: Shut down services
      run: docker-compose down
