name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run services
      run: docker-compose up --build -d

    - name: Wait for Keycloak to be ready
      run: |
        echo "Waiting for 60 seconds for Keycloak to start..."
        sleep 60

    - name: Run tests
      run: docker-compose exec app go test -v ./...

    - name: Run linters
      run: |
        docker-compose exec app go install golang.org/x/lint/golint@latest
        docker-compose exec app golint ./...

    - name: Shut down services
      run: docker-compose down
